version: 2

# lib-uncommons is a Go library (no binary to build).
# GoReleaser is used only for changelog generation and GitHub release creation.

builds:
  - skip: true

changelog:
  sort: asc
  filters:
    exclude:
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "Breaking Changes"
      regexp: "^.*breaking[(\\w)]*:+.*$"
      order: 0
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 10
    - title: "Improvements"
      regexp: "^.*chore[(\\w)]*:+.*$"
      order: 20
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 30
    - title: "Security Updates"
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 40
    - title: "Documentation Updates"
      regexp: ^.*?docs(\([[:word:]]+\))??!?:.+$
      order: 50
    - title: "Tests"
      regexp: ^.*?(test(s)?(\([[:word:]]+\))?)!?:.+$
      order: 60
    - title: Other Work
      order: 999
